### ISSUE TITLE
Please support connection strings

### ISSUE THREAD

**Issue by chiptech-kirk** [agmoss/winston-azure-blob#10]
Hi there, I've put in a PR for supporting connection strings.
https://github.com/agmoss/winston-azure-blob/pull/9
This also allows using the package with Azurite.

Feel free to rework it if you feel it is too hacky putting the connection string in the account name property.

Thanks very much for the package by the way!

**Comment by agmoss** [comment]
Hi @chiptech-kirk, thanks for the flag. I have updated your pr with some better ergonomics for handling a connection string in the account type. I will merge and publish soon.

**Comment by agmoss** [comment]
Available in version `1.4.0` https://www.npmjs.com/package/winston-azure-blob/v/1.4.0
