### ISSUE TITLE
Mention that syncTimeout option is in milliseconds

### ISSUE THREAD

**Issue by quintesse** [agmoss/winston-azure-blob#12]
It wasn't really clear and I had to look at the code to see that it uses `setTimeout()` and then I had to look at the docs for that function to learn it is in milliseconds. Changing the text simply to something like "The maximum time in milliseconds between two sync calls. Set to zero for real-time logging" would be nice.

**Comment by agmoss** [comment]
@quintesse Thanks for submitting this. I have updated the API docs to read better and specify milliseconds.
