### ISSUE TITLE
Make `extension` accept a string

### ISSUE THREAD

**Issue by quintesse** [agmoss/winston-azure-blob#14]
Right now the only thing that `extension` accepts is a value of type `extensions` which limits us to only create files that either don't have an extension (`extension === undefined`) or that have an extension of ".log". In our case we want a different extension but there's no way to "extend" the enumeration with new values.

I would suggest a change to make `extension` simply accept any string value. One can still use the `extensions` enumeration if one wants but one can also use any other desired value.

The change is minimal but very useful.

A work-around is to use `extension: ".my_ext" as any`.

**Comment by agmoss** [comment]
Good call @quintesse . I will release `1.4.2` with this functionality.

**Comment by quintesse** [comment]
Thanks! 🙂
