### ISSUE TITLE
Allow custom header for new blobs

### ISSUE THREAD

**Issue by quintesse** [agmoss/winston-azure-blob#16]
We're using the latest feature that allows us to change file/blob extensions to write log CSV files/blobs (don't ask why) and it would be really nice if we were able to write a custom header, containing the column names, to each new blob that gets created.

Detecting that a new blob gets created is pretty easy, you just need to check that the result of [appendBlobClient.createIfNotExists()](https://github.com/agmoss/winston-azure-blob/blob/main/lib/winston-azure-blob.ts#L216) has the field `succeeded` set to `true` (see [docs](https://learn.microsoft.com/en-us/javascript/api/%40azure/storage-blob/appendblobcreateifnotexistsresponse?view=azure-node-latest#@azure-storage-blob-appendblobcreateifnotexistsresponse-succeeded)).

Simply being able to pass a header, eg. `header: "My custom header"`, in the options would be enough and would really help.

Edit: changed "file" to "blob"

**Comment by agmoss** [comment]
So I think to facilitate this functionality we would check if the blob is newly created then append the headers to the blob before appending any content. Something like: 

```typescript
    private static async appendBlobOperation(
        appendBlobClient: AppendBlobClient,
        chunk: string,
        nextAppendBlock: async.ErrorCallback<Error>,
        headers?: string
    ) {
        try {
            const { succeeded } = await appendBlobClient.createIfNotExists();

            if (succeeded && headers) { // Blob is newly created and user defined csv header's are present
                await appendBlobClient.appendBlock(headers, headers.length);
            }

            const result = await appendBlobClient.appendBlock(
                chunk,
                chunk.length
            );
            if (result.errorCode) {
                debug(result.errorCode, result);
            }
        } catch (err) {
            debug(err);
        } finally {
            nextAppendBlock();
        }
    }
```

It could be more elegant to provide the headers as a `headers?: Array<string>`. What do you think?

**Comment by quintesse** [comment]
> What do you think?

I think that would be perfect 👍

**Comment by agmoss** [comment]
I will include this functionality in release `1.5.0`

**Comment by quintesse** [comment]
Great! Will try this first thing tomorrow. Thanks.

**Comment by quintesse** [comment]
Forgot to give an update: works perfectly, thanks!
