### ISSUE TITLE
Option to set file extension

### ISSUE THREAD

**Issue by kieran-reportabl** [agmoss/winston-azure-blob#2]
Currently you can upload log files as [blobName].[rotatePeriod]

Would it be possible to add the option to set file extension?

**Current**
``` javascript
  import * as winston from "winston";
  import { winstonAzureBlob } from "winston-azure-blob";

  const logger = winston.createLogger({
    format: winston.format.combine(
        winston.format.timestamp(),
        winston.format.splat(),
        winston.format.json()
    ),
    transports: [
      winstonAzureBlob({
        account: { ... },
        containerName: "logs",
        blobName: "requests",
        level: "info",
        bufferLogSize : 1,
        syncTimeout : 0,
        rotatePeriod : "YYYY-MM-DD",
        eol : "\n"
      })
    ]
  });
  ```
  
  **Expected output in Azure Blob** 
  `logs/requests.2022-05-23`
  
  **Proposed**
``` javascript
  import * as winston from "winston";
  import { winstonAzureBlob, extensions } from "winston-azure-blob";

  const logger = winston.createLogger({
    format: winston.format.combine(
        winston.format.timestamp(),
        winston.format.splat(),
        winston.format.json()
    ),
    transports: [
      winstonAzureBlob({
        account: { ... },
        containerName: "logs",
        blobName: "requests",
        level: "info",
        bufferLogSize : 1,
        syncTimeout : 0,
        rotatePeriod : "YYYY-MM-DD",
        eol : "\n",
        extension : extensions.LOG // ".log" if other options could be added, or just a true/false flag for ".log" only
      })
    ]
  });
```

  **Expected output in Azure Blob** 
  `logs/requests.2022-05-23.log`

**Comment by agmoss** [comment]
Hi @kieran-reportabl, 

Thanks for documenting this. I think it is a great idea!

To promote extensibility I think the enum proposal (`extensions.LOG`) is the way to go. I will make a pr and subsequent release in the next couple of days. 

Is there anything else you would like to see from this library?

**Comment by kieran-reportabl** [comment]
Hi @agmoss,

Apologies for late response. Good to hear! Appreciate the quick update.

At present this was the only change I was hoping to see. The library has otherwise been very good and easy to work with.

**Comment by agmoss** [comment]
Awesome! I'm glad you have found it useful. Cheers.
