### ISSUE TITLE
Blob is not getting created after certain period of time

### ISSUE THREAD

**Issue by sasidhar8785** [agmoss/winston-azure-blob#8]
I have created a Nodejs application and using PM2 I am running the process. This process log all the logs to blob in azure on hourly basis. It appears that blob creation is not happening for every hour. Unless we restart the process in PM2, it will not work. After restart it will work for some more time and then it will stop working.

**Comment by agmoss** [comment]
Hi @sasidhar8785, thanks for informing me of this. Can you share a minimum reproducible example or elaborate on how you have set this up? I will need more context to look into this.

**Comment by sasidhar8785** [comment]
Hi @agmoss ,

Here is the code sample which I am using.

const { winstonAzureBlob, extensions } = require("winston-azure-blob");

const blobpath = hostName + '/' + date.getFullYear() + '/' + (date.getMonth() + 1) + '/' + date.getDate();
var transport = new winstonAzureBlob({
    account: {
        name: blob_name,
        key: blob_key
    },
    blobName: blobpath + '/sm-beta-v2-' + PORT,
    bufferLogSize: 1,
    containerName: blob_containername,
    eol: "\n",
    extension: extensions.LOG,
    level: "info",
    rotatePeriod: "YYYY-MM-DD-HH",
    syncTimeout: 0,
});

transport.on('rotate', function (oldFilename, newFilename) {
    console.log(oldFilename);
    console.log(newFilename);
});

var logger = winston.createLogger({
    transports: [
        transport,
        esTransport
    ]
});

Run the application for 3-4 hours and keep on sending logs every min, then you will see that after some time blob in the folder it supposed to be created wont create.

Here are the packages that I am using.
![image](https://user-images.githubusercontent.com/51992223/198822585-042ff204-a064-468a-82ca-2af88535ba1b.png)

BTW, I am using both elastic and blob for the logs.

**Comment by agmoss** [comment]
Thanks for sharing this, @sasidhar8785. I have been a bit busy recently. I will take a look at this over the weekend. Cheers!

**Comment by agmoss** [comment]
Hi @sasidhar8785, 

I am not sure I can reproduce the issue. I can see created blobs at the `rotatePeriod` specified. Are you trying to have a new folder created for each `rotatePeriod`? If so, you would need to alter your `blobpath` variable to include hours. 

I have a reproduction example [here](https://github.com/agmoss/winston-azure-blob/blob/num8/examples/number8.js). This has package scripts for node and pm2. I am using a `rotatePeriod` that includes `SS` for brevity. Check it out to see if I am missing anything.
